### ISSUE TITLE
Timer capture fields definition

### ISSUE THREAD

**Issue by GatorCh** [rambutan32/librambutan#12]
Hi,

Found that input/output capture fields definition have some mistakes in timer.h
This is due to STM32 having some registers fields swapped while the include file
followed the obvious sequence. `INPUT_TI1/2` and `INPUT_TI3/4` values `CC1/2S` 
and `CC3/4S` have swapped values. 
Had to change a few names to make fields name unique to registers. 

Should be fixed as below, `_OUTPUT` and `_INPUT_TRC` can remain as is. Working
on a previous release so cannot generate a proper diff, sorry.
```
/* Capture/compare mode registers, common values */

#define TIMER_CCMR_CCS_OUTPUT          0x0
#define TIMER_CCMR_CCS_INPUT_TRC       0x3

/* Capture/compare mode register 1 (CCMR1) */

#define TIMER_CCMR_CC1S_INPUT_TI1       0x1
#define TIMER_CCMR_CC1S_INPUT_TI2       0x2

#define TIMER_CCMR_CC2S_INPUT_TI1       0x2
#define TIMER_CCMR_CC2S_INPUT_TI2       0x1

...
#define TIMER_CCMR1_CC2S_INPUT_TI1      (TIMER_CCMR_CC2S_INPUT_TI1 << 8)
#define TIMER_CCMR1_CC2S_INPUT_TI2      (TIMER_CCMR_CC2S_INPUT_TI2 << 8)

...
/* Capture/compare mode register 2 (CCMR2) */

#define TIMER_CCMR_CC3S_INPUT_TI3       0x1
#define TIMER_CCMR_CC3S_INPUT_TI4       0x2

#define TIMER_CCMR_CC4S_INPUT_TI3       0x2
#define TIMER_CCMR_CC4S_INPUT_TI4       0x1

...
#define TIMER_CCMR1_CC4S_INPUT_TI3      (TIMER_CCMR_CC4S_INPUT_TI3 << 8)
#define TIMER_CCMR1_CC4S_INPUT_TI4      (TIMER_CCMR_CC4S_INPUT_TI4 << 8)
```
Cheers,
Serge

**Comment by bnewbold** [comment]
Oh geez, look at that! Eg, Section 15.4.7 of RM0008 (STM32F1 series) and Section 12.4.7 of RM0368 (STM32F4 series) confirm:
```
CC2S: Capture/Compare 2 selection
  01: CC2 channel is configured as input, IC2 is mapped on TI2
  10: CC2 channel is configured as input, IC2 is mapped on TI1

CC1S: Capture/Compare 1 selection
  01: CC1 channel is configured as input, IC1 is mapped on TI1
  10: CC1 channel is configured as input, IC1 is mapped on TI2
```
(etc)

The relevant lines in current master include (but may not be limited to):
* https://github.com/rambutan32/librambutan/blob/master/libmaple/include/libmaple/timer.h#L382
* https://github.com/rambutan32/librambutan/blob/master/libmaple/include/libmaple/timer.h#L414

Serge, thanks so much for catching this! I'm going to need to review a bunch of register maps and write a test case to confirm this bug, i'll try to push a fix soon.

Sorry it took me so long to reply, my mail server was down for a day or two. Also, I've edited your comment to be monospace, hope you're ok with that.
